-- Disable Row Level Security (RLS) for all tables
-- This allows the application to read/write data without authentication policies
-- For production, you should implement proper RLS policies instead

ALTER TABLE IF EXISTS app_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sale_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS client_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplier_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplier_order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supplier_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS treasury_transactions DISABLE ROW LEVEL SECURITY;
